# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  workflow_dispatch:

env:
  BUBBLEWRAP_MANIFEST_URL: ${{ vars.BUBBLEWRAP_MANIFEST_URL }}
jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/googlechromelabs/bubblewrap:latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Init bubblewrap
      shell: bash
      run: printf 'y\ny\n' | bubblewrap init --manifest $BUBBLEWRAP_MANIFEST_URL




    