# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  workflow_dispatch:

env:
  BUBBLEWRAP_MANIFEST_URL: ${{ vars.BUBBLEWRAP_MANIFEST_URL }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install bubblewrap
      run: yes | npm i -g @bubblewrap/cli

    - name: Initialize bubblewrap
      run: bubblewrap init --manifest=$BUBBLEWRAP_MANIFEST_URL